import localFont from 'next/font/local'
import './globals.css'
import Footer from '@/components/shared/Footer'

// Load custom fonts
const font1 = localFont({
  src: './fonts/font1.ttf',
  variable: '--font-heading',
})

const font2 = localFont({
  src: './fonts/font2.ttf',
  variable: '--font-paragraph',
})

const font3 = localFont({
  src: './fonts/font3.ttf',
  variable: '--font-button',
})

const playfair = localFont({
  src: './fonts/PlayfairDisplay-VariableFont_wght.ttf',
  variable: '--font-playfair',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${font1.variable} ${font2.variable} ${font3.variable} ${playfair.variable} antialiased`}
      >
        {children}
        <Footer />
      </body>
    </html>
  )
}
